import pytest

from transliterator.scripts import spaced_nasal, transliterate

# Public-domain verses (and one short invocation in the style of the real books, with Vedic accent
# marks). The expected text was generated by Aksharamukha 2.3 and then read by eye: it pins the
# behaviour against drift (a library bump, a changed option), it is not an independent oracle.
GOLDEN = [
    pytest.param(
        "ఓం భూర్భువస్సువః । తత్సవితుర్వరేణ్యం భర్గో దేవస్య ధీమహి । ధియో యో నః ప్రచోదయాత్ ॥",
        "ॐ भूर्भुवस्सुवः । तत्सवितुर्वरेण्यं भर्गो देवस्य धीमहि । धियो यो नः प्रचोदयात् ॥",
        "oṃ bhūrbhuvassuvaḥ | tatsaviturvareṇyaṃ bhargo devasya dhīmahi | dhiyo yo naḥ pracodayāt ||",
        "ಓಂ ಭೂರ್ಭುವಸ್ಸುವಃ । ತತ್ಸವಿತುರ್ವರೇಣ್ಯಂ ಭರ್ಗೋ ದೇವಸ್ಯ ಧೀಮಹಿ । ಧಿಯೋ ಯೋ ನಃ ಪ್ರಚೋದಯಾತ್ ॥",
        id="gayatri",
    ),
    pytest.param(
        "శుక్లాంబరధరం విష్ణుం శశివర్ణం చతుర్భుజం । ప్రసన్నవదనం ధ్యాయేత్ సర్వవిఘ్నోపశాంతయే ॥",
        "शुक्लांबरधरं विष्णुं शशिवर्णं चतुर्भुजं । प्रसन्नवदनं ध्यायेत् सर्वविघ्नोपशांतये ॥",
        "śuklāmbaradharaṃ viṣṇuṃ śaśivarṇaṃ caturbhujaṃ | prasannavadanaṃ dhyāyet sarvavighnopaśāntaye ||",
        "ಶುಕ್ಲಾಂಬರಧರಂ ವಿಷ್ಣುಂ ಶಶಿವರ್ಣಂ ಚತುರ್ಭುಜಂ । ಪ್ರಸನ್ನವದನಂ ಧ್ಯಾಯೇತ್ ಸರ್ವವಿಘ್ನೋಪಶಾಂತಯೇ ॥",
        id="shukla-ambaradharam",
    ),
    pytest.param(
        "ఓం సహ నావవతు । సహ నౌ భునక్తు ॥ ఓం శాంతిః శాంతిః శాంతిః ॥",
        "ॐ सह नाववतु । सह नौ भुनक्तु ॥ ॐ शांतिः शांतिः शांतिः ॥",
        "oṃ saha nāvavatu | saha nau bhunaktu || oṃ śāntiḥ śāntiḥ śāntiḥ ||",
        "ಓಂ ಸಹ ನಾವವತು । ಸಹ ನೌ ಭುನಕ್ತು ॥ ಓಂ ಶಾಂತಿಃ ಶಾಂತಿಃ ಶಾಂತಿಃ ॥",
        id="shanti",
    ),
    pytest.param(
        "శ్రీ॒ గు॒రు॒భ్యో॒ న॒మః॒ .... హరిః ఓమ్ ....",
        "श्री॒ गु॒रु॒भ्यो॒ न॒मः॒ ॥॥ हरिः ओम् ॥॥",
        "śrī̱ gu̱ru̱bhyo̱ na̱ma̱ḥ .... hariḥ om ....",
        "ಶ್ರೀ॒ ಗು॒ರು॒ಭ್ಯೋ॒ ನ॒ಮಃ॒ .... ಹರಿಃ ಓಂ ....",
        id="invocation-with-vedic-accents",
    ),
    pytest.param(
        "అన్యానస్మద్గురూన్ సన్తత మానతోఽస్మి ||",
        "अन्यानस्मद्गुरून् सन्तत मानतोऽस्मि ||",
        "anyānasmadgurūn santata mānato'smi ||",
        "ಅನ್ಯಾನಸ್ಮದ್ಗುರೂನ್ ಸಂತತ ಮಾನತೋಽಸ್ಮಿ ||",
        id="avagraha-and-explicit-nasal",
    ),
]


@pytest.mark.parametrize(("te", "sa", "en", "kn"), GOLDEN)
def test_golden(te, sa, en, kn):
    assert transliterate(te, "sa") == sa
    assert transliterate(te, "en") == en
    assert transliterate(te, "kn") == kn


def test_indic_dandas_option_is_what_keeps_the_telugu_danda():
    # The option's function is a pass-through but the library keys off its name: without it `।`
    # becomes `.` in IAST and Kannada. Guards against anyone "cleaning up" the options.
    assert transliterate("ఓం ।", "kn") == "ಓಂ ।"
    assert transliterate("ఓం ।", "en") == "oṃ |"


def test_anusvara_before_a_stop_becomes_the_matching_nasal_in_english():
    assert transliterate("సంకల్ప", "en") == "saṅkalpa"
    assert transliterate("సంకల్ప", "sa") == "संकल्प"


def test_whitespace_and_line_breaks_are_preserved():
    assert transliterate("సం  కల్పం", "en") == "saṃ  kalpaṃ"
    assert transliterate("త్రినేత్రం భజే\nకామాక్షీం", "sa") == "त्रिनेत्रं भजे\nकामाक्षीं"


@pytest.mark.parametrize("text", ["", "   ", "\n"])
def test_blank_text_comes_back_unchanged(text):
    assert [transliterate(text, s) for s in ("sa", "en", "kn")] == [text] * 3


def test_digits_follow_the_target_script():
    # Inherited from Aksharamukha: ASCII and Telugu digits are both rewritten as the target's
    # digits for Indic scripts and as ASCII for IAST. Verse numbers are stripped at import, so this
    # only shows when a stray digit survives in a verse.
    assert transliterate("abc 123 ౧౨౩", "sa") == "abc १२३ १२३"
    assert transliterate("abc 123 ౧౨౩", "kn") == "abc ೧೨೩ ೧೨೩"
    assert transliterate("abc 123 ౧౨౩", "en") == "abc 123 123"


# ── The spaced anusvara rule (English, opt-in) ──────────────────────────────────────────────────


@pytest.mark.parametrize(
    ("iast", "expected"),
    [
        ("trinetraṃ bhaje", "trinetram bhaje"),
        ("trinetraṁ bhaje", "trinetram bhaje"),
        ("tvāṃ kṣamasva", "tvāṅ kṣamasva"),
        ("saṃ ca", "sañ ca"),
        ("saṃ ṭa", "saṇ ṭa"),
        ("saṃ tat", "san tat"),
        ("saṃ\u00a0pra", "sam\u00a0pra"),  # a no-break space counts, and is kept
        ("saṃkalpa", "saṅkalpa"),  # nothing in between: also covers the adjacent case
        ("aha\u0331ṃ\u0331 tvā", "aha\u0331n\u0331 tvā"),  # Vedic accent after the ṃ
    ],
)
def test_spaced_nasal_rewrites_across_spaces_and_accents(iast, expected):
    assert spaced_nasal(iast) == expected


@pytest.mark.parametrize(
    "iast",
    [
        "saṃ | tvā",  # a danda blocks it
        "saṃ, tvā",
        "saṃ 1 tvā",
        "kāmākṣīṃ\nkāmākṣīṃ",  # a line break blocks it: it ends one verse line, starts none
        "saṃ yo",  # y is not a stop
        "oṃ",
        "saṃ",
    ],
)
def test_spaced_nasal_leaves_everything_else_alone(iast):
    assert spaced_nasal(iast) == iast


def test_spaced_nasal_is_opt_in_and_only_for_english():
    te = "త్రినేత్రం భజే"
    assert transliterate(te, "en") == "trinetraṃ bhaje"
    assert transliterate(te, "en", spaced_nasal_rule=True) == "trinetram bhaje"
    assert transliterate(te, "sa", spaced_nasal_rule=True) == transliterate(te, "sa")
    assert transliterate(te, "kn", spaced_nasal_rule=True) == transliterate(te, "kn")


def test_spaced_nasal_keeps_line_end_anusvaras_when_run_through_the_pipeline():
    te = "కామాక్షీం\nకామాక్షీం"
    assert transliterate(te, "en", spaced_nasal_rule=True) == "kāmākṣīṃ\nkāmākṣīṃ"


def test_spaced_nasal_agrees_with_the_default_rule_where_both_apply():
    # The spaced rule replaces the default one rather than running after it, so it has to cover
    # the directly-adjacent case identically and only add the across-a-space one.
    te = "సంకల్ప సంగ్రహం తం దేవం"
    assert transliterate(te, "en") == "saṅkalpa saṅgrahaṃ taṃ devaṃ"
    assert transliterate(te, "en", spaced_nasal_rule=True) == "saṅkalpa saṅgrahan tan devaṃ"
